### ISSUE TITLE
[Request]  Ability to adjust font size and/or use (clearer) alternative font?

### ISSUE THREAD

**Issue by gwiede** [thomasokken/plus42desktop#3]
The default font can be a bit difficult to read (3's vs 9's, for example), so it would be great if we could adjust the sizing of the font within the display.  Ideally, if we could select a different font (SwissMicros forums have a few donations worth exploring), that'd be even better.

I looked extensively in the docs for Free42 and Plus42 because I really believed there was already something available in layout settings or such, but if such settings exist, I was unable to locate them.  Unrelated, but a single consolidated Plus42 manual (instead of a delta from Free42) would be helpful, and likewise w.r.t. layout file formatting.

**Comment by gwiede** [comment]
Here's a picture of what I mean w.r.t. 3's & 9's...

![plus42screen_2022-06-23_13-18](https://user-images.githubusercontent.com/86432346/175393397-0d12e63b-ab63-4eb0-b683-fe6f1c409730.png)

Note the '3' in "6.232..." is difficult to distinguish from a '9' (at least here, on my display).  It's an odd case, no question, but a vexing one as well -- I wasn't even aware I might misread '3' as '9' until I saw the above after u2t unixtime conversion and realized it wasn't 6.29.  Anyway, nothing earth-shatteringly critical, feel free to ignore, and thanks for your endless work on both Free42 and Plus42!!!

**Comment by thomasokken** [comment]
I'm not seeing it myself, I think the 3 and 9 look quite different. If I'm going to confuse any two digits, it will be the 3 and 8...
But of course this is subjective, what is clear to one person may not be to another, and vice versa.

I have selectable high-res fonts on my long-term to-do list, and that would fix the issue. Note that "long-term" in this case means "not soon," since changing the display logic to support other fonts — and high-res graphics, which I want to implement at the same time — is a change that will require a lot of work, and it is not yet clear when I will be able to make the time for that.

Just know that this is on my radar. I am closing the issue here.

**Comment by sbridger** [comment]
DisplaySize:scale_y can help with this:

DisplaySize: 22,2 18 3 3 #cols,rows disp_y pixel_scale_y max_rows
![image](https://github.com/thomasokken/plus42desktop/assets/850648/b77c0fbf-2e28-4797-8450-cffec3222eef)

DisplaySize: 22,2 18 2 3
![image](https://github.com/thomasokken/plus42desktop/assets/850648/1cb1ce71-bd61-4797-8d6f-8c53e177c119)
