### ISSUE TITLE
Top (blank) row buttons mimicking row "Σ+" through "XEQ" by default

### ISSUE THREAD

**Issue by gwiede** [thomasokken/plus42desktop#5]
Unclear if intentional or not, but by default as of 1.0.11, the top (blank) row of buttons in Plus42 now do the same as the buttons in the row "Σ+" through "XEQ", which is surprising, unexpected (and arbitrary) behavior.   I do not recall this being their behavior in 1.0.10 or prior, but could be misremembering in that regard, feels like new behavior in 1.0.11.

Please advise if intentional, and if so, would be nice if there was a preference to have them do nothing instead (until assigned).

P.S. Thanks for "A..F" function!

-John Wiederhirn

**Comment by thomasokken** [comment]
The top row actually is the same as the top row of the HP-42S keyboard, only without the labels on the keys. The second and third rows are the rows that were added to create the Plus42 keyboard layout.
The behavior of the top row when no menu is active is therefore the same as that of the top row of the HP-42S.
Plus42 has behaved this way from the beginning. It would require extra code to not make it behave this way, and that doesn't seem useful to me.
I realize that this behavior may be surprising, which is why I dedicated an FAQ entry to it, but I think it's harmless, so I won't change it.

**Comment by gwiede** [comment]
If I had to guess, I suspect I was unprepared because this is an area where DM42 behaves differently than free42 (at least with the PMP extension active, I tend to forget I have that installed), combined with them not mimicking the top row proper.  

I get what you're saying about it replicating the free42 / hp42s behavior.  Still, for plus42 I suspect it'd still be less jarring/surprising, if plus42 top row must mimic a row, to have it mimic the plus42 second row, instead of the free42 / hp42s top row (aka plus42 third row, which accentuates it feeling somewhat arbitrary).  Minor nit, however, so get if leaving it alone is felt to be best soln overall.  Thanks!

**Comment by sbridger** [comment]
The problem with this is that you can't override the non-menu function of the buttons, without losing menu function.
So it becomes a row of buttons with no function except when the menu is up, or a wasted duplicate of the existing row. 
I suggest the key function in .layout is amended to add separate key number for MenuDisplayed mode. This is only used for the top row of keys

Key:  Normal,Shifted,MenuDisplayed
