### ISSUE TITLE
Possability of "backporting" CAS features from newer HP RPN calculators?

### ISSUE THREAD

**Issue by duplexsystem** [thomasokken/plus42desktop#8]
Since you've been adding features from other HP calculators to Plus42 I'm curious as to the possibility of backpacking CAS features from newer HP calculators? 

Thanks and I appreciate all the work you've done on Free/Plus42!

**Comment by duplexsystem** [comment]
I should add that the CAS system used in new HP RPN calculators is open source under a compatible license (LGPL) see: http://www-fourier.ujf-grenoble.fr/~parisse/english.html#hpcalc

**Comment by thomasokken** [comment]
I have some additional CAS functionality on my to-do list, though not particularly high. I'm thinking of the 28/48 features first, i.e. applying operators and functions to expressions (so you can do 'A' 'B' + => 'A+B' or 'A' SIN => 'SIN(A)', etc.), symbolic differentiation, and ISOL.
More heavyweight CAS functionality, i.e. symbolic integration, simplification, and maybe other things, would be nice, but I haven't really thought about it yet. It would have to be based on a freely-available third-party library, because I don't have the time to build a full-blown CAS system myself. I know there are such libraries, but I'm not sure if they are compatible with the Android and iOS app stores. I remember reading that GPLv3 is not compatible with the iOS app store, but I don't know if this is true for the  LGPL as well.
