### ISSUE TITLE
UNITS? function is missing

### ISSUE THREAD

**Issue by mgrubb** [thomasokken/plus42desktop#9]
I'm running Plus42 1.0.19 (decimal) on MacOS 13.3.1 (Ventura) on an Intel Mac.
The UNITS? function as mentioned in the documentation doesn't appear in either the catalog or the UNIT.FCN menu.
There's no up/down indicator when the UNIT.FCN menu is displayed.
![image](https://github.com/thomasokken/plus42desktop/assets/351301/8dce39d4-8ff8-4ca6-9671-d11d4376396c)

**Comment by thomasokken** [comment]
The function you're looking for is actually called UNIT?, not UNITS?, and it can be found in CATALOG → UNIT, and in PGM.FCN and CATALOG → FCN while in the equation editor. Because it seemed like something that would be of use primarily in EQN mode, it didn't seem like something that would be used frequently enough in normal mode to require putting it in the UNIT.FCN menu, though I will concede that it's not unreasonable to expect to find it there.
